### PR TITLE
Darshan Diamond

### PR DESCRIPTION
**Pull request by darshandiamond**
Program works with argument added after shell script.

### CODE REVIEW

**Comment by Skeegan123** [comment]
I am not super familiar with Java but I believe we were instructed to not include any binary files, but it looks like you have one  called fizbuz.class. Other than that it looks pretty good

**Comment by darshandiamond** [comment]
> I am not super familiar with Java but I believe we were instructed to not include any binary files, but it looks like you have one called fizbuz.class. Other than that it looks pretty good

Thanks for pointing that out.  I think I have deleted it now.  I hope it worked,

**Review by Skeegan123 — COMMENTED** [review]
+1 Looks good to me!

**Comment by cameronwilcox** [comment]
It looks like the logic will work, but I guess just in the spirit of the assignment, you could just have if statments that check if the number is divisible by three and five, and if a number is divisible by both then it will hit both and print "Fizz" and then "Buzz" and then have an if statment to see if it's divisible by neither. That way you could cut down on one statement (in this case your else statement). Then just print a new line after all of it.

**Comment by cameronwilcox** [comment]
+10 Code ran and worked without errors 
DarshanJava

**Review by cameronwilcox — COMMENTED** [review]
+1 It looks like the logic will work, but I guess just in the spirit of the assignment, you could just have if statments that check if the number is divisible by three and five, and if a number is divisible by both then it will hit both and print "Fizz" and then "Buzz" and then have an if statment to see if it's divisible by neither. That way you could cut down on one statement (in this case your else statement). Then just print a new line after all of it.

**Pull request merged**
