### PR TITLE
updating my html to include some content

### PR DESCRIPTION
**Pull request by laytonmccafferty**

### CODE REVIEW

**Review by Skeegan123 — CHANGES_REQUESTED** [review]
Looks like you have a couple errors. Your html tags are a bit messed up for the linkedln and portfolio website items

**Comment by laytonmccafferty** [comment]
> Looks like you have a couple errors. Your html tags are a bit messed up for the linkedln and portfolio website items

I updated the ending tags for these! it should all look good now. (:

**Review by Skeegan123 — CHANGES_REQUESTED** [review]
So close. You need a "</a>" tag on your linkedln line. Right now you just have a closing "</li>" tag

**Comment by laytonmccafferty** [comment]
> So close. You need a closing "a" tag on your linkedln line. Right now you just have a closing "li" tag

ah i see! html will be the death of me i swear... i think its correct now then!

**Review by Skeegan123 — APPROVED** [review]
You got it! Looks good!

**Pull request merged**
