### PR TITLE
Adding my FizzBuzz soultion and files. Updated index.html as well.

### PR DESCRIPTION
**Pull request by JamesLucas943**

### CODE REVIEW

**Review by Skeegan123 — COMMENTED** [review]
+1 Havent tested but no blaring issues as far as I can tell. Nice concise solution!

**Review by laytonmccafferty — CHANGES_REQUESTED** [review]
Somewhere in your program, there needs to be the condition of being both divisible by 5 and 3, which will subsequently print fizzbuzz!

**Comment by JamesLucas943** [comment]
> Somewhere in your program, there needs to be the condition of being both divisible by 5 and 3, which will subsequently print fizzbuzz!

Both tests are run on each number. if the number is divisible by 3, then it prints Fizz. Then the code checks if that same number is divisible by 5. And, if it is, then Buzz is printed. Therefore, if the number is divisible by both 3 and 5, then FizzBuzz will be printed. This output will also be on the same line because I used sys.stdout.write() rather than print().

**Comment by JamesLucas943** [comment]
> Somewhere in your program, there needs to be the condition of being both divisible by 5 and 3, which will subsequently print fizzbuzz!

Both tests are run on each number. if the number is divisible by 3, then it prints Fizz. Then the code checks if that same number is divisible by 5. And, if it is, then Buzz is printed. Therefore, if the number is divisible by both 3 and 5, then FizzBuzz will be printed. This output will also be on the same line because I used sys.stdout.write() rather than print().

**Review by laytonmccafferty — APPROVED** [review]
alright, I see what you're saying now with the code! That would be my bad for just reading over it a bit too fast! +1 for sure and i'll pull it down to my machine right now to make sure it works!

**Review by laytonmccafferty — DISMISSED** [review]
Screen Shot 2023-03-09 at 9 04 13 AM
When trying to run your program, I'm faced with this error about permissions. In order to fix this, all you need to do is be in the James directory and run the command `chmod +x run.sh`

**Comment by laytonmccafferty** [comment]
okay! I can pull down the changes and take a look again to see if its working correctly now 😊

**Comment by Skeegan123** [comment]
Just pulled down and attempted to run it. Only issue was that the python command does not work on my computer. After I changed it to python3 it ran correctly. I know that another person was also using python but was able to change it to python3 and it worked on their computer as well as others. Maybe try that and see if both will work on your computer? If not then I believe it is just an issue with me although I cannot seem to fix it for some reason. Let me know what you decide to do.

**Review by Siertischek — APPROVED** [review]
+10 The code seems to work for me. I had to install a different version of python using sudo apt-get install python but thats due to the way that different systems were referencing the different versions by using python3 vs python when the version switch happened. The only minor issue that I got was that some parentheses were added to the fizz and buzz in the output.
image

**Comment by JamesLucas943** [comment]
> Just pulled down and attempted to run it. Only issue was that the python command does not work on my computer. After I changed it to python3 it ran correctly. I know that another person was also using python but was able to change it to python3 and it worked on their computer as well as others. Maybe try that and see if both will work on your computer? If not then I believe it is just an issue with me although I cannot seem to fix it for some reason. Let me know what you decide to do.

I tried to change it to python3, but no luck on my end. I am not too sure if it has to do with python version, but i should be all updated to the most recent version. So, Im not sure what to do to fix that to make it more universal?

**Comment by JamesLucas943** [comment]
> okay! I can pull down the changes and take a look again to see if its working correctly now 😊

Did that work for you now Layton?

**Pull request merged**
