### PR TITLE
Added submission for Keegan Gaffney

### PR DESCRIPTION
**Pull request by Skeegan123**
Added Keegan Gaffney's Typescript solution to FizzBuzz. Documentation is in the README and index.html. Shell script checks for dependancies and compiles the program. Added .gitignore

### CODE REVIEW

**Review by laytonmccafferty — CHANGES_REQUESTED** [review]
the .gitignore file can be removed, but im not sure about the extra typescript files. +1 because the overall code looks good, even if im not very familiar w the language

**Comment by Skeegan123** [comment]
When we talked about it in class a couple weeks ago I believe Devin said to use a gitignore to prevent the .DS_Store files from being added. And I looked into the extra typescript files as well. From my limited research it apears they are required to compile properly.

**Comment by laytonmccafferty** [comment]
alright! it still says there are some merge conflicts in your .gitignore file, so anyway you can take care of those would be great (: otherwise, it won't be able to merge!

I just pulled down your code on a checked out local branch and I am using homebrew on Mac to install npm and then subsequently install typescript and install node too. For anyone else wondering, these are the commands that I ran:
```
brew install npm
npm install -g typescript
npm install node
```

After reading your README.md, i ran the following commands and got the following output:

Screen Shot 2023-03-10 at 2 20 38 PM

This looks great to me! README.md is very easy to follow and took me no time at all to install the required packages to make all of the dependencies work! As an added bonus, the web page for this looks amazing as well. Great work! +10

**Comment by Skeegan123** [comment]
Alright I should be able to merge now if you accept those changes, Thanks!

**Review by laytonmccafferty — APPROVED** [review]
Nice work!

**Pull request merged**
