### PR TITLE
java-FizzBuzz

### PR DESCRIPTION
**Pull request by zdjewett**
Added "java1" directory for java files ('1' was required to avoid packaging name error)
Added index, readme, .java, .class, .sh files for FizzBuzz
Updated home directory index with personal link

Thanks:)

### CODE REVIEW

**Review by Skeegan123 — COMMENTED** [review]
+1 Looks good I will pull it down and test it real quick

**Review by Skeegan123 — APPROVED** [review]
You need to apply the right permissions using the command ```chmod +x FizzBuzzShell.sh``` then re commit FizzBuzzShell.sh but I will approve it so you arent stuck anymore. +10 Runs good after updating permissions

**Comment by darshandiamond** [comment]
Be careful not to include the .class file.  It is a binary file.

**Comment by zdjewett** [comment]
thanks guys, I'll take care of those rn

**Comment by corrosivecamel** [comment]
Looks good I will pull try testing this +1

**Pull request merged**
