### PR TITLE
Fizzbuzz/cameron wilcox rust new

### PR DESCRIPTION
**Pull request by cameronwilcox**
New pull request for Cameron Wilcox

### CODE REVIEW

**Review by Skeegan123 — COMMENTED** [review]
+1 I dont know rust but the logic looks good so far, only thing iI dont know is if Cargo.toml is needed. Ill pull it down and try it myself.

**Comment by Skeegan123** [comment]
Alright after attempting to run the program I got the following output:

Screenshot 2023-03-10 at 6 27 47 PM

First error was that I did not have permision to use ./run.sh. This can be fixed with the command ```chmod +x run.sh```. The second error had something to do with a ] being expected. This probably has to do with the script since it happened before the compile but I do not know for sure.

**Comment by Skeegan123** [comment]
So I was able to get it to run with ./run.sh, but that was after I had to run source run.sh because you have that chmod command in the script. This works but isnt ideal. I believe if you run the chmod command in your own terminal then commit run.sh the correct permissions should trannsfer as well, then you dont even need it in your run.sh script. Let me know if that makes sense and if not I will try to explain it again.

**Comment by cameronwilcox** [comment]
@Skeegan123 if you look at the files changed I added the chmod +x part to the script

**Comment by cameronwilcox** [comment]
@Skeegan123 did you pull down the new changes?

**Comment by Skeegan123** [comment]
@cameronwilcox Yes I pulled down the changes and yes I saw the change in the script, however, having that command in the script doesnt really solve the problem. This is because you need to run that command to be able to run it properly in the first place. The chmod command changes the permissions on the file making it so that anyone can run it. If you dont have the permissions to run it, it wont get to the part in the script where it changes its own permissions. If you run the command on your own computer before you add and commit the file, the file should commited to the repo with the correct permissions. That way you dont even need that line in the script because it already has the correct permissions. Does that make sense? I can try to explain it again if needed

**Comment by cameronwilcox** [comment]
@Skeegan123 yea I got that part and I actually did push the file with the correct permissions.as well as add it to the file. Why it's not working is the part I'm actually confused about.

**Comment by Skeegan123** [comment]
@cameronwilcox hmm. Then I am confused too lol. You still dont need that command in the script because that commands purpose is to give the permission to run it which isnt needed if you can already run it. But as for why I dont already have the permissions if you commited the file with the correct permissions is definitley weird. Other than that, after running the command myself and running the program everything else seems to work fine.

**Comment by cameronwilcox** [comment]
@Skeegan123 I'll try pushing it again sometime today

**Comment by Skeegan123** [comment]
@cameronwilcox Yea I'll look out for that. I dont think its a windows thing but it is possible, if that doesnt work we can either ask Devin or just call it good because other than that the output looks good

**Review by Skeegan123 — APPROVED** [review]
+10, that seemed to fix the permissions issue for me somehow. And runs as expected. Nice job!

**Comment by JamesLucas943** [comment]
I looked at the code and it all looks good. Also, the comments helped me fix my executable error with that 'git update-index --chmod=+x run.sh' command. So, thank you, and +1.

**Pull request merged**
